"""
Tweet category definitions and helpers.

Defines the TweetCategory enum and utility functions for category parsing
and conversion used throughout the application.
"""

from enum import Enum


class TweetCategory(str, Enum):
    """
    Categories for classifying tweets.

    Each category represents a different business intent:
    - COMPETITOR_COMPLAINT: User frustrated with a competitor
    - SOLUTION_SEEKER: User looking for solutions Yara provides
    - BRAND_MENTION: Direct mention of Yara.cash
    - IRRELEVANT: Tweet that doesn't fit our engagement criteria
    """
    COMPETITOR_COMPLAINT = "competitor-complaints"
    SOLUTION_SEEKER = "solution-seekers"
    BRAND_MENTION = "brand-mentions"
    IRRELEVANT = "irrelevant"


# Mapping of aliases to canonical categories
_CATEGORY_ALIASES: dict[str, TweetCategory] = {
    # Brand mentions
    "brand": TweetCategory.BRAND_MENTION,
    "brand-mention": TweetCategory.BRAND_MENTION,
    "brand-mentions": TweetCategory.BRAND_MENTION,
    "mention": TweetCategory.BRAND_MENTION,
    "mentions": TweetCategory.BRAND_MENTION,
    # Competitor complaints
    "competitor": TweetCategory.COMPETITOR_COMPLAINT,
    "competitor-complaint": TweetCategory.COMPETITOR_COMPLAINT,
    "competitor-complaints": TweetCategory.COMPETITOR_COMPLAINT,
    "complaint": TweetCategory.COMPETITOR_COMPLAINT,
    "complaints": TweetCategory.COMPETITOR_COMPLAINT,
    # Solution seekers
    "seeker": TweetCategory.SOLUTION_SEEKER,
    "seekers": TweetCategory.SOLUTION_SEEKER,
    "solution": TweetCategory.SOLUTION_SEEKER,
    "solution-seeker": TweetCategory.SOLUTION_SEEKER,
    "solution-seekers": TweetCategory.SOLUTION_SEEKER,
}


def parse_smoke_category(raw_value: str | None) -> TweetCategory | None:
    """
    Parse a category string from user input (e.g., Discord commands).

    Accepts various aliases and normalizes them to canonical TweetCategory.
    Returns None if the input doesn't match any known category.
    Defaults to BRAND_MENTION if raw_value is None.

    Args:
        raw_value: Raw category string from user input

    Returns:
        TweetCategory if recognized, None otherwise
    """
    if raw_value is None:
        return TweetCategory.BRAND_MENTION

    normalized = raw_value.strip().lower().replace("_", "-").replace(" ", "-")
    return _CATEGORY_ALIASES.get(normalized)


def category_to_hint(category: TweetCategory) -> str:
    """
    Convert a TweetCategory to its hint string for AI classification.

    The hint is used in search queries and passed to AI classifiers
    to help with categorization.

    Args:
        category: The TweetCategory to convert

    Returns:
        Hint string (e.g., "competitor_complaint", "solution_seeker")
    """
    mapping = {
        TweetCategory.COMPETITOR_COMPLAINT: "competitor_complaint",
        TweetCategory.SOLUTION_SEEKER: "solution_seeker",
        TweetCategory.BRAND_MENTION: "brand_mention",
    }
    return mapping.get(category, "brand_mention")


def is_local_test_tweet_id(tweet_id: str) -> bool:
    """
    Check if a tweet ID is a locally-generated test ID.

    Test tweet IDs are generated by !smoke and !ingest commands
    and should not be posted to the actual X platform.

    Args:
        tweet_id: The tweet ID to check

    Returns:
        True if this is a test tweet ID
    """
    return tweet_id.startswith(("smoke-", "manual-"))
